import BaseEntity from './BaseEntity';

class DeviceEntity extends BaseEntity {
	constructor() {
		super();
		this.id = null;
		this.id_device = null;
		this.id_project = null;
		this.id_device_type = null;
		this.name = null;
		this.model = null;
		this.serial_number = null;
		this.manufacturer = null;
		this.installed_at = null;
		this.description = null;
		this.status = 1;
		this.is_virtual = 1;
		this.created_date = null;
		this.created_by = null;
		this.updated_date = null;
		this.updated_by = null;
		this.menu_order = 0;
		this.sp_sunrise_sunset = null;
		this.sp_dc_current_threshold = null;
		this.sp_time_threshold = null;
		this.sp_ratio = null;
		this.enable_performance_index = 0;
		this.enable_string_performance = 0;
		this.enable_device_faults = 0;
		this.enable_zeo_generation = 0;
		this.enable_system_disconnect = 0;
		this.pi_index_value = null;
		this.inverter_efficiency = 0.96;
		this.system_losses = 0.045;
		this.temperature_coefficient = -0.47;
		this.pi_sunrise_sunset = 0.5;
		this.pi_time_threshold = 0.25;
		this.zg_sunrise_sunset = 0.5;
		this.zg_time_threshold = 0.25;
		this.sd_sunrise_sunset = 0.25;
		this.sd_time_threshold = 0.25;
		this.max_ac_output = null;
		this.panel_temperature = null;
		this.poa_irradiance = null;
		this.dc_size = null;
		this.dc_current_string01 = 0;
		this.dc_current_string02 = 0;
		this.dc_current_string03 = 0;
		this.dc_current_string04 = 0;
		this.dc_current_string05 = 0;
		this.dc_current_string06 = 0;
		this.dc_current_string07 = 0;
		this.dc_current_string08 = 0;
		this.dc_current_string09 = 0;
		this.dc_current_string10 = 0;
		this.dc_current_string11 = 0;
		this.dc_current_string12 = 0;
		this.dc_current_string13 = 0;
		this.dc_current_string14 = 0;
		this.dc_current_string15 = 0;
		this.dc_current_string16 = 0;
		this.dc_current_string17 = 0;
		this.dc_current_string18 = 0;
		this.dc_current_string19 = 0;
		this.dc_current_string20 = 0;
		this.dc_current_string21 = 0;
		this.dc_current_string22 = 0;
		this.dc_current_string24 = 0;
		this.dc_current_string24 = 0;
		this.sp_type = 1;
		this.pi_type = 1;
	}
}
export default DeviceEntity;